In [19]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [20]:
test = pd.read_csv('C:/Users/adith/Desktop/Datasets/emnist-letters-test.csv')
train = pd.read_csv('C:/Users/adith/Desktop/Datasets/emnist-letters-train.csv')
train.head()

23  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.406  0.407  0.408  \
0   7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  16  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  15  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  23  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  17  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.409  0.410  0.411  0.412  0.413  0.414  0.415  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [29]:
y1 = np.array(train.iloc[:,0].values)
x1 = np.array(train.iloc[:,1:].values)
y2 = np.array(test.iloc[:,0].values)
x2 = np.array(test.iloc[:,1:].values)
print(y1.shape)
print(x1.shape)
print(y2.shape)
print(x2.shape)
m = 88799

(88799,)
(88799, 784)
(14799,)
(14799, 784)


In [30]:
# x = x1[np.any([y1==1,y1==2],axis=0)]
# y = y1[np.any([y1==1,y1==2],axis=0)]
# x_t = x2[np.any([y2==1,y2==2],axis=0)]
# y_t = y2[np.any([y2==1,y2==2],axis=0)]

In [31]:
X_train = x1.transpose()/255.0
Y_train = y1.reshape(1,y1.shape[0])-1
X_test = x2.transpose()/255.0
Y_test = y2.reshape(1,y2.shape[0])-1
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(784, 88799)
(1, 88799)
(784, 14799)
(1, 14799)


In [38]:
def init_params():
    W1 = np.random.rand(26, 784) - 0.5
    b1 = np.random.rand(26, 1) - 0.5
    W2 = np.random.rand(26, 26) - 0.5
    b2 = np.random.rand(26, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 100= 0:
            print("Iteration:010 i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

SyntaxError: invalid syntax (Temp/ipykernel_7696/3091328836.py, line 61)

In [40]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 1.00, 1000)

Iteration:  0
[18 18 19 ... 18 17 18] [[ 6 15 14 ...  0 22 11]]
0.044324823477741866
Iteration:  10
[ 1 13 22 ...  1  1 17] [[ 6 15 14 ...  0 22 11]]
0.07796258966880258
Iteration:  20
[17 15 22 ...  1  1 17] [[ 6 15 14 ...  0 22 11]]
0.1317244563564905
Iteration:  30
[14 15 14 ... 12 22 17] [[ 6 15 14 ...  0 22 11]]
0.17000191443597337
Iteration:  40
[14 15 14 ... 12 22  1] [[ 6 15 14 ...  0 22 11]]
0.22948456626763816
Iteration:  50
[ 3 15 14 ...  7 22  1] [[ 6 15 14 ...  0 22 11]]
0.2794288223966486
Iteration:  60
[ 3 15 14 ...  7 22 11] [[ 6 15 14 ...  0 22 11]]
0.33560062613317715
Iteration:  70
[ 3 15 14 ... 23 22  8] [[ 6 15 14 ...  0 22 11]]
0.3498575434408045
Iteration:  80
[ 3 15 14 ... 25 22  8] [[ 6 15 14 ...  0 22 11]]
0.37057849750560257
Iteration:  90
[ 3 15  2 ... 25 22  8] [[ 6 15 14 ...  0 22 11]]
0.4086082050473541
Iteration:  100
[ 3 15  2 ... 25 22  8] [[ 6 15 14 ...  0 22 11]]
0.41739208774873593
Iteration:  110
[ 3 15  6 ... 25 22  8] [[ 6 15 14 ...  0 22 11]]
0.