In [49]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


In [50]:
test = pd.read_csv("C:/Users/adith/Desktop/Datasets/Polynomial_test.csv")
train = pd.read_csv("C:/Users/adith/Desktop/Datasets/Polynomial_train.csv")

train = (train - np.min(train)) / (np.max(train) - np.min(train))
test = (test - np.min(test)) / (np.max(test) - np.min(test))
test.head()


Unnamed: 0         X         Y         Z     label
0      0.0000  0.966123  0.520763  0.799372  0.348891
1      0.0001  0.640607  0.807332  0.821102  0.361912
2      0.0002  0.366511  0.888973  0.153398  0.416444
3      0.0003  0.150386  0.039686  0.542708  0.146510
4      0.0004  0.578721  0.389405  0.801596  0.426142

In [51]:
train = train.drop(["Unnamed: 0"], axis = 1)
test = test.drop(["Unnamed: 0"], axis = 1)
train.head()

X         Y         Z     label
0  0.231825  0.006202  0.210584  0.461451
1  0.188043  0.282876  0.065016  0.442035
2  0.128716  0.370154  0.409481  0.391436
3  0.027649  0.366191  0.695569  0.426798
4  0.334706  0.469617  0.835697  0.387717

In [53]:
X = train.values[:, :-1]
Y = train.values[:, -1].reshape(train.values.shape[0], 1)

X_test = test.values[:, :-1]
Y_test = test.values[:, -1].reshape(test.values.shape[0], 1)

print(X)
print(Y)
print(X.shape)
print(Y.shape)
print(X_test.shape)
print(Y_test.shape)

[[0.2318255  0.00620153 0.2105835 ]
 [0.18804274 0.28287559 0.06501568]
 [0.1287159  0.3701538  0.40948095]
 ...
 [0.36192257 0.32432986 0.47638034]
 [0.29530506 0.65766616 0.26104849]
 [0.23138369 0.8550764  0.3404406 ]]
[[0.46145137]
 [0.44203495]
 [0.39143578]
 ...
 [0.50172725]
 [0.37895592]
 [0.34741488]]
(50000, 3)
(50000, 1)
(10000, 3)
(10000, 1)


In [39]:
X = np.vstack((np.ones((X.shape[0], )), X.T)).T
X_test = np.vstack((np.ones((X_test.shape[0], )), X_test.T)).T
print(X)

[[1.         0.2318255  0.00620153 0.2105835 ]
 [1.         0.18804274 0.28287559 0.06501568]
 [1.         0.1287159  0.3701538  0.40948095]
 ...
 [1.         0.36192257 0.32432986 0.47638034]
 [1.         0.29530506 0.65766616 0.26104849]
 [1.         0.23138369 0.8550764  0.3404406 ]]


In [44]:
def model(X, Y, learning_rate, no_of_iterations):
    m_train = Y.size
    theta = np.zeros((X.shape[1], 1))
    cost_list = []
    
    for i in range(no_of_iterations):
        y_pred = np.dot(X, theta) + np.dot(X**2, theta) + np.dot(X**3, theta)
        cost = (1/(2*m_train))*np.sum(np.square(y_pred - Y))
        
        grad = (1/m_train)*np.dot(X.T, y_pred - Y)
        theta -=learning_rate*grad
        
        cost_list.append(cost)
        
        if(i%(no_of_iterations/10) == 0):
            print('Cost is :', cost)

    return theta, cost_list

In [45]:
iteration = 1000
lr = 0.05
theta, cost_list = model(X, Y, learning_rate =lr ,no_of_iterations = iteration)

Cost is : 0.10094464481451891
Cost is : 0.009653889395262622
Cost is : 0.009389725559477754
Cost is : 0.009332635962552011
Cost is : 0.009318033596067333
Cost is : 0.009313237545174605
Cost is : 0.009311152625563866
Cost is : 0.009310028501579259
Cost is : 0.009309340252595152
Cost is : 0.009308888356866362


In [46]:
y_pred = np.dot(X_test, theta) + np.dot(X_test**2, theta) + np.dot(X_test**3, theta)
error = (1/X_test.shape[0])*np.sum(np.abs(y_pred - Y_test))
rmse = np.sqrt(((y_pred-Y_test)**2).mean())
print("Test error is:", error*100,"%")
print(rmse)
print("Test accuracy is :", (1-error)*100, "%")

Test error is: 10.298251802715699 %
0.14066813470215275
Test accuracy is : 89.7017481972843 %
